# 포트 번호 변경

server:
  port: 9090

# database 연결

spring:
  datasource:
    url: jdbc:mysql://localhost/taco
    username: root
    password: tiger
    driver-class-name: com.mysql.jdbc.Driver

# 애플리케이션이 시작될 때 데이터베이스를 초기화하는 SQL 스크립트의 실행

spring:
  datasource:
    schema:
      - order-schema.sql
      - ingredient-schema.sql
      - taco-schema.sql
      - user-schema.sql
    data:
      - ingredients.sql

# DEBUG 수준으로 설정

logging:
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG


# 로그 파일을 수록하고 싶다면

logginf:
  path: /var/logs/
  file: Taco.log
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG


# 프로덕션 환경 속성 지정

---
spring:
  profiles: prod
  datasources:
    url: jdbc:mysql://localhost/taco
    username: root
    password: tiger

logging:
  level:
    tacos: WARN